### ISSUE TITLE
Weber–Fechner law

### ISSUE THREAD

**Issue by DHD-Harper** [HarperEhlersProjects/SmartHome_LED_Master_RaspberryPi3#18]

**Comment by svenehlers** [comment]
may will me solved by a gamma correction LUT

**Comment by svenehlers** [comment]
implemented by gamma correction

**Comment by svenehlers** [comment]
https://hackaday.com/2016/08/23/rgb-leds-how-to-master-gamma-and-hue-for-perfect-brightness/
